### PR TITLE
Implement theme support for font controls with Typecase.

### PR DESCRIPTION
**Pull request by chriswallace**

### CODE REVIEW

**Comment by ataylorme** [comment]
> There's just one weird little behavior that seems off. When you select "Advanced" and open a section, things toggle weirdly. 

@chriswallace I just tested this again and don't see any issue. Can you review one more time? I think the customizer/panel changes are ready to go to master and then on to wordpress.org if you approve.

**Comment by ataylorme** [comment]
> Third note is we should add the ability to enable font size tweaks for certain selectors. I can see it being useful for headings or body text 

@chriswallace is this still functionality you want to add?

**Comment by ataylorme** [comment]
> Third note is we should add the ability to enable font size tweaks for certain selectors. I can see it being useful for headings or body text

@chriswallace I have this implemented and tested with TwentyFifteen. The font-size is there for body text, article title, block quotes, and list items. I did not add headings since the font selector there is H1-H6 and they are different sizes.

See the [font-size branch(https://github.com/UpThemes/Typecase/tree/font-size)

Let me know when you have a chance to review. If you approve of the implementation I can add font size selectors for the other default themes.

Here are a few screenshots

### Customizer
screen shot 2015-01-16 at 11 38 18 am]

### Front-End
screen shot 2015-01-16 at 11 37 55 am

**Comment by michaelbeil** [comment]
@chriswallace @ataylorme anybody reviewed this lately? Looks like a fresh pull of master is needed in this branch for the PR to be merge-able.

**Comment by ataylorme** [comment]
@michaelbeil I chatted with @angela-crist last week. [Here is the relevant Basecamp thread](https://basecamp.com/1761770/projects/9345528/todos/177507524)

**Comment by ataylorme** [comment]
@chriswallace Assigning to you for review and merge to master

**Comment by michaelbeil** [comment]
Waiting on the master ...

**Comment by garand** [comment]
Honorary master here, let's go with this and iterate from this point. :+1:

**Comment by michaelbeil** [comment]
Perfecto yo.

**Pull request merged**
